FROM node:20-alpine
WORKDIR /app

ENV NODE_ENV=production

COPY .env .env
COPY . .

RUN npm install -g pnpm

RUN rm -f .npmrc
RUN pnpm install --prod --ignore-scripts --frozen-lockfile --prefer-offline
RUN pnpm build

EXPOSE 3000

CMD ["pnpm", "start"]