FROM node:20-alpine as build
WORKDIR /app

ENV NODE_ENV=production

COPY . .

RUN npm install -g pnpm

RUN pnpm install --prod=false --ignore-scripts --frozen-lockfile --prefer-offline
RUN pnpm build

FROM node:20-alpine
WORKDIR /app

ENV NODE_ENV=production

COPY --from=build /app /app

EXPOSE 3000

CMD ["npm", "start"]